import React,{useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
const presets={agachamento:{label:'Agachamento',tag:'PERNAS',phase:'squat'},legpress:{label:'Leg Press',tag:'MÁQUINA',phase:'legpress'},supino:{label:'Supino',tag:'PEITO',phase:'bench'},supinoinclinado:{label:'Supino Inclinado',tag:'PEITO',phase:'incline'},remada:{label:'Remada',tag:'COSTAS',phase:'row'},puxada:{label:'Puxada',tag:'COSTAS',phase:'latpull'},desenvolvimento:{label:'Desenvolvimento',tag:'OMBROS',phase:'shoulder'},rosca:{label:'Rosca Direta',tag:'BÍCEPS',phase:'curl'},triceps:{label:'Tríceps na Polia',tag:'TRÍCEPS',phase:'pushdown'},crucifixo:{label:'Crucifixo',tag:'PEITO',phase:'fly'},abdominal:{label:'Abdominal',tag:'CORE',phase:'crunch'},elevacao:{label:'Elevação Lateral',tag:'OMBROS',phase:'lateral'}};
function createMan(scene){const skin=new THREE.MeshStandardMaterial({color:0xd6a27a,roughness:.72}),shirt=new THREE.MeshStandardMaterial({color:0x334155,roughness:.58}),shorts=new THREE.MeshStandardMaterial({color:0x111827,roughness:.7}),shoe=new THREE.MeshStandardMaterial({color:0xe5e7eb,roughness:.5});const root=new THREE.Group();scene.add(root);const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.42,.9,8,16),shirt);torso.scale.set(.82,1,.62);torso.position.y=1.65;root.add(torso);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.13,.15,.16,16),skin);neck.position.y=2.22;root.add(neck);const head=new THREE.Mesh(new THREE.SphereGeometry(.27,24,18),skin);head.position.y=2.56;head.scale.set(.92,1.08,.9);root.add(head);const hip=new THREE.Group();hip.position.y=1.15;root.add(hip);const pelvis=new THREE.Mesh(new THREE.CapsuleGeometry(.34,.3,8,12),shorts);pelvis.scale.set(1,.8,.7);hip.add(pelvis);const parts={root,torso,hip,arms:[],forearms:[],thighs:[],shins:[]};for(const side of [-1,1]){const upper=new THREE.Group();upper.position.set(side*.48,2,0);root.add(upper);const ua=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.58,8,12),skin);ua.position.y=-.28;upper.add(ua);const elbow=new THREE.Group();elbow.position.set(side*.54,1.55,0);root.add(elbow);const fa=new THREE.Mesh(new THREE.CapsuleGeometry(.105,.5,8,12),skin);fa.position.y=-.25;elbow.add(fa);const thigh=new THREE.Group();thigh.position.set(side*.2,1.08,0);hip.add(thigh);const tm=new THREE.Mesh(new THREE.CapsuleGeometry(.18,.72,8,12),shorts);tm.position.y=-.38;thigh.add(tm);const knee=new THREE.Group();knee.position.set(side*.2,.38,0);hip.add(knee);const sm=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.7,8,12),skin);sm.position.y=-.36;knee.add(sm);const foot=new THREE.Mesh(new THREE.CapsuleGeometry(.13,.35,8,12),shoe);foot.scale.z=1.5;foot.rotation.z=Math.PI/2;foot.position.set(side*.2,-.76,.12);knee.add(foot);parts.arms.push(upper);parts.forearms.push(elbow);parts.thighs.push(thigh);parts.shins.push(knee)}return parts}
function Demo3D({exercise,playing}){const ref=useRef(null),playingRef=useRef(playing);playingRef.current=playing;useEffect(()=>{const host=ref.current;if(!host)return;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(3.4,2.35,5.8);camera.lookAt(0,1.35,0);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;host.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xcbd5e1,0x0f172a,2.4));const key=new THREE.DirectionalLight(0xffffff,3.4);key.position.set(3,5,4);key.castShadow=true;scene.add(key);const rim=new THREE.PointLight(0x60a5fa,18,8);rim.position.set(-3,2,2);scene.add(rim);const floor=new THREE.Mesh(new THREE.CylinderGeometry(2.25,2.25,.08,64),new THREE.MeshStandardMaterial({color:0x111827,roughness:.82}));floor.position.y=-.02;scene.add(floor);const ring=new THREE.Mesh(new THREE.RingGeometry(1.55,1.58,64),new THREE.MeshBasicMaterial({color:0x38bdf8,transparent:true,opacity:.25,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.025;scene.add(ring);const man=createMan(scene),p=presets[exercise.id]||presets.agachamento;let t=0,last=performance.now();function resize(){const w=host.clientWidth||320,h=host.clientHeight||320;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)}resize();const ro=new ResizeObserver(resize);ro.observe(host);let raf;function animate(now){const dt=Math.min(.04,(now-last)/1000);last=now;if(playingRef.current)t+=dt;const s=(Math.sin(t*Math.PI*1.45)+1)/2;man.root.rotation.y=Math.sin(t*.65)*.08;man.hip.position.y=1.15;man.torso.rotation.set(0,0,0);man.arms.forEach(a=>a.rotation.set(0,0,0));man.forearms.forEach(a=>a.rotation.set(0,0,0));man.thighs.forEach((a,i)=>a.rotation.z=i?-.04:.04);man.shins.forEach((a,i)=>a.rotation.z=i?.04:-.04);
if(p.phase==='squat'){man.hip.position.y=1.15-s*.38;man.thighs.forEach((a,i)=>a.rotation.z=(i?-.38:.38)*s);man.shins.forEach((a,i)=>a.rotation.z=(i?.48:-.48)*s);man.torso.rotation.z=-.06*s}
if(p.phase==='legpress'){man.root.rotation.z=.08;man.thighs.forEach((a,i)=>a.rotation.z=(i?-.65:.65)*s);man.shins.forEach((a,i)=>a.rotation.z=(i?.7:-.7)*s)}
if(p.phase==='bench'||p.phase==='incline'){man.root.rotation.z=p.phase==='incline'?.28:.02;man.root.position.y=.22;man.arms.forEach((a,i)=>a.rotation.z=(i?-.42:.42)*s);man.forearms.forEach((a,i)=>a.rotation.z=(i?.58:-.58)*s)}
if(p.phase==='row'){man.torso.rotation.z=.18;man.arms.forEach((a,i)=>a.rotation.z=(i?-.3:.3)*s);man.forearms.forEach((a,i)=>a.rotation.z=(i?.55:-.55)*s)}
if(p.phase==='latpull'){man.arms.forEach((a,i)=>a.rotation.z=(i?-.9:.9)*(1-s));man.forearms.forEach((a,i)=>a.rotation.z=(i?.7:-.7)*(1-s))}
if(p.phase==='shoulder'||p.phase==='lateral'){man.arms.forEach((a,i)=>a.rotation.z=(i?-.95:.95)*s)}
if(p.phase==='curl'){man.forearms.forEach((a,i)=>a.rotation.z=(i?-.95:.95)*s)}
if(p.phase==='pushdown'){man.forearms.forEach((a,i)=>a.rotation.z=(i?.75:-.75)*s)}
if(p.phase==='fly'){man.arms.forEach((a,i)=>a.rotation.z=(i?-.78:.78)*s)}
if(p.phase==='crunch'){man.torso.rotation.z=-.25*s;man.hip.position.y=1.15-.08*s}
renderer.render(scene,camera);raf=requestAnimationFrame(animate)}raf=requestAnimationFrame(animate);return()=>{cancelAnimationFrame(raf);ro.disconnect();renderer.dispose();host.removeChild(renderer.domElement)}},[exercise.id]);return <div ref={ref} className="real3DCanvas" aria-label={'Demonstração 3D de '+exercise.name}/> }
export default function Exercise3DDemo({exercise,playing:controlledPlaying}){const [internalPlaying,setInternalPlaying]=useState(true);const playing=typeof controlledPlaying==='boolean'?controlledPlaying:internalPlaying,p=presets[exercise.id]||presets.agachamento;return <section className="exerciseDemo premiumDemo"><div className="exerciseDemoHead"><div><span>GUIA 3D • {p.tag}</span><h3>{p.label}</h3></div><button className={playing?'demoToggle active':'demoToggle'} onClick={()=>setInternalPlaying(v=>!v)}>{playing?'Pausar':'Reproduzir'} <span>▶</span></button></div><div className="real3DStage"><div className="real3DBadge">3D • MOVIMENTO REALISTA</div><Demo3D exercise={exercise} playing={playing}/><div className="real3DCue"><b>Observe a repetição completa</b><span>Modelo 3D interativo para visualizar postura e trajetória.</span></div></div><div className="motionSteps"><span><b>1</b>Posição inicial</span><span><b>2</b>Movimento controlado</span><span><b>3</b>Retorno</span></div></section>}

